
# MB_channels =  [
# ("UCX6OQ3DkcsbYNE6H8uQQuVA", "MrBeast"),
#  ("UCluBATXIP9doWvougjUVUGQ", "MrBeast На Русском"),
#  ("UCDifkiOICEJ-hiVAvCQlpNA", "MrBeast हिन्दी"),
#  ("UCbHU7ouxaMgfyWSUtI4QK8Q", "MrBeast in Arabic"),
#  ("UCNAhW2oJvy_FUU082pEDspA", "MrBeast en Español"),
#  ("UCggERuskO1F6XKwor-Pvkww", "MrBeast Brasil"),
#  ("UCbf2Ozi4BF34AY3t3rHj9IA", "MrBeast en Français"),
#  ("UClwITvsAr6JnpLmGufudiTw", "MrBeast Japan"),
#  ("UCUaT_39o1x6qWjz7K2pWcgw", "Beast Reacts"),
#  ("UCneluyh2H6gU7v8gU8El-Cg", "Beast Reacts em Português"),
#  ("UCLAVIBJWb6geGRSvWsZ_ang", "Beast Reacts На Русском"),
#  ("UCL6Xc5xuRECnWbGBOKG9APA", "Beast Reacts en Español"),
#  ("UCIPPMRA040LQr5QPyJEbmXA", "MrBeast Gaming"),
#  ("UC1lZ05QnM1R09HiwNMLDdnw", "MrBeast Gaming На Русском"),
#  ("UCfNGT03h99S3zLbyUD9FMuQ", "MrBeast Gaming en Español"),
#  ("UCpPJaHR_s3qYSCzry78G7lg", "MrBeast Gaming Brasil"),
#  ("UC4-79UOlP48-QNGgCko5p2g", "MrBeast 2"),
#  ("UCAiLfjNXkNv24uhpzUgPa6A", "Beast Philanthropy"),
#  ("UCZzvDDvaYti8Dd8bLEiSoyQ", "MrBeast 3"),
#  ("UC68DIXWCmetC8N5J_Kc5gjQ", "Don't Subscribe"),
# ]

channels =  [
    (  'T-Series',  'UCq-Fj5jknLsUf-MWSy4_brA'),
    (  'T-Series Kids Hut',  'UChz5aEi3dfrDVC8-YJsMUDA'),
    (  'T-Series Apna Punjab',  'UCcvNYxWXR_5TjVK7cSCdW-g'),
    (  'T-Series Telugu',  'UCnJjcn5FrgrOEp5_N45ZLEQ'),
    (  'T-Series Kannada',  'UCovxnbWKPCA5iJDxa9zbBew'),
    (  'Shabad Gurbani',  'UC884UDwNldmpdEiS1mgtijA'),
    (  'Health And Fitness',  'UCBFc--hZlA7MvH9MdwA2xLQ'),
    (  'T-Series Bhakti Sagar',  'UCaayLD9i5x4MmIoVZxXSv_g'),
    (  'Pop Chartbusters',  'UCzL6rJhkoXkIt0fCv9T9_uA'),
    (  'Bollywood Classics',  'UCZ_OLiS7DkyCg89eV_qQMoQ'),
    (  'T-Series Tamil',  'UCoi3aLlLa6xs0A1QwR_7oxA'),
    (  'T-Series Malayalam',  'UCUoj77TIUy9DhLNe5EVmF-A'),
    (  'T-Series Classical',  'UCH_dFsLe_I0ftAFP8XzJkTQ'),
    (  'T-Series Regional',  'UCy2fvV-mH_4AcIgqnLg9uDw'),
    (  'T-Series Hamaar Bhojpuri',  'UCpN-WGQgGsOrXm7nHXDdTDA'),
    (  'T-Series Gujarati',  'UCev6abkwjdHj_dB3rquFfbQ'),
    (  'T-Series Marathi',  'UCCo_LMj-m3iGSSuytYq9n6Q'),
    (  'T-Series Bhavageethegalu & Folk', 'UCJKd5H8WR_w0wN-Or1-MJyQ'),
    (  'Bhakti Sagar Telugu',  'UCjA7qIB2IetzeolMd_Hwa0w'),
    (  'Bhakti Sagar Tamil',  'UCg5bqGqi_ROdCPV4eHF575g'),
    (  'Bhakti Sagar Malayalam',  'UCG-dSI2eRCBzxzPUfXjxHQw'),
    (  'T-Series Bhakti Marathi',  'UCR4_gSSeup7YpBfsOWN_oRA'),
    (  'Bhakti Sagar Kannada',  'UCQX4SV8Fg0cD98K1VRBVPEw'),
    (  'T-Series Islamic Music',  'UCVkXfARLNI0vf7gajoDDjlw'),
    (  'T-Series Kids Hut - Por. Fairy Tales', 'UCz2pmzVJkW78zzUNIN0GeTQ'),
    (  'T-Series Haryanvi',  'UC-pCOUhn4BBB4yAz9I2KJ-A'),
    (  'T-Series Kids Hut ESP',  'UCBlslL5pqbe8EwI1Edx__Fw'),
    (  'T-Series Kids Hut Tamil',  'UCoi3aLlLa6xs0A1QwR_7oxA'),
    (  'Lahari Karaoke I T-Series',  'UCZ8_6qvdkJQEhyXQEkEtQAQ'),
    (  'T-Series StageWorks Academy',  'UCmrXfts0Dsq9QfX257GeDeQ'),
    (  'Lahari Music',  'UCnSqxrSfo1sK4WZ7nBpYW1Q'),
    (  'Lahari Music Telugu',  'UCyhgNoFwssv3hG-gc29sEnw'),
    (  'Lahari Music Malayalam',  'UCBi7UD8gdi_SCLX7dZjKVeQ'),
    (  'Lahari Music Tamil',  'UCN5cwheKFtBXLQCss18UgpA'),
    (  'Lahari Music Kannada',  'UC3nd8KWMTo8w_KOyPBs1HsA'),
    (  'Bhakti Lahari Telugu',  'UC9VpXeB0L74sOIMTg-PQT-A'),
    (  'Bhakti Lahari Sanskrit',  'UC91yw44h6LhazKipp_ToWUw'),
    (  'Bhakti Lahari Tamil',  'UCDVDaxrGbc0g4QGgOh1lcqQ'),
    (  'Bhakti Lahari Kannada',  'UCOb2IJpMET6r45eM-vzALiQ'),
    (  'T-Series Himachali',  'UC6rzGFfqiyOTxIGhx7MDJYA'),
    (  'T-Series Kashmiri Music',  'UClvpZMFJC3nE6Lup1Ota5iA'),
    (  'T-Series Movies',  'UCJMUG6U-HzZI4fkz5a7movA'),
    (  'Lahari Bhavag. & Folk',  UCXNtS5Od_4Njr6J5YJo2uyg),
    (  'Lahari Classical',  'UCsQMWfiNhYtxVss-Z1Z2Aww'),
    (  'Lahari Janapada Geethegalu', 'UCGi7QIJEPTi09j37z7kY2qg'),
    (  'Lahari Comedy T-Series',  'UCJySEUaIQjMA3uvCXh12qRA'),
    (  'T-Series Rajasthani',  'UCkPipkv-8UZ2saO2TjE8AWA')
    ]